#!/usr/bin/env python3

# Run a test server.

import os
import argparse
parser = argparse.ArgumentParser(description='get dir')
parser.add_argument('--dir', type=str, help='dir', default=os.getcwd(), required=False)
parser.add_argument('--host', type=str, help='host', default='127.0.0.1', required=False)
args = parser.parse_args()

directory = os.path.abspath(args.dir)

flexible_link = os.path.dirname(__file__)+"/app/static/flexible"

if os.path.islink(flexible_link):
    os.unlink(flexible_link)
os.symlink(directory, flexible_link)

print("Opening directory {}".format(directory))

from app import app, db
from app.qasi.model import Image

try:
    Image.query.all()
except:
    db.create_all()

app.run(host=args.host)
